---
name: Upgrade workflows

on:
  schedule:
    - cron: "0 9 * * 1" # every Monday at 9:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod

      - name: Install bumpwf
        run: go install github.com/hatedabamboo/bumpwf@latest

      - name: Upgrade workflows
        run: |
          env
          ls -l "$GOPATH"
          $GOPATH/bumpwf -A -s -v

      - name: Create labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh label create chore --color 0075ca --force
          gh label create dependencies --color 0075ca --force
          gh label create automated --color e4e669 --force

      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          commit-message: "chore: upgrade workflow action versions"
          branch: chore/upgrade-workflow-actions
          delete-branch: true
          title: "chore: upgrade workflow action versions"
          body: "Automated upgrade of GitHub Actions versions by
            [bumpwf](https://github.com/hatedabamboo/bumpwf)."
          labels: chore,dependencies,automated
